# Copyright (c) 2021, 2022 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
# 
---

- hosts: target_hosts 
  tasks:
    - name: Uninstalling the Management Agent
      become: yes
      become_user: root
      shell: 
        "rpm -e oracle.mgmt_agent"

   