apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mgmtagent
  namespace: {{ default "mgmtagent" .Values.namespace }}
  labels:
    app: mgmtagent
spec:
  serviceName: mgmtagent
  replicas: 1
  selector:
    matchLabels:
      app: mgmtagent
  template:
    metadata:
      labels:
        app: mgmtagent
    spec:
      securityContext:
        runAsUser: {{ default 0 .Values.deployment.security.runAsUser }}
        runAsGroup: {{ default 0 .Values.deployment.security.runAsGroup }}
        fsGroup: {{ default 0 .Values.deployment.security.fsGroup }}
      serviceAccountName: mgmtagent-serviceaccount
      imagePullSecrets:
        - name: mgmtagent-container-registry-key
      restartPolicy: Always
      containers:
        - name: mgmtagent
          image: {{ .Values.mgmtagent.image.url }}
          resources:
            requests:
              cpu: {{ .Values.deployment.resource.request.cpuCore }}
              memory: {{ .Values.deployment.resource.request.memory }}
            limits:
              cpu: {{ .Values.deployment.resource.limit.cpuCore }}
              memory: {{ .Values.deployment.resource.limit.memory }}
          volumeMounts:
            - name: mgmtagent-secret
              mountPath: /opt/oracle/mgmtagent_secret
              readOnly: true
            - name: mgmtagent-pvc
              mountPath: /opt/oracle
            - name: mgmtagent-config
              mountPath: /opt/oracle/mgmtagent_config
            - mountPath: /tmp
              name: tmp
          securityContext:
           allowPrivilegeEscalation: false
           readOnlyRootFilesystem: true
      volumes:
        - name: mgmtagent-secret
          secret:
            secretName: mgmtagent-input-rsp
        - name: mgmtagent-config
          configMap:
            name: mgmtagent-monitoring-config
        - emptyDir: {}
          name: tmp
  volumeClaimTemplates:
    - metadata:
        name: mgmtagent-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        {{- if .Values.deployment.storageClass }}
        storageClassName: {{ .Values.deployment.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.deployment.resource.request.storage }}
